# Librerías y configuraciones

In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_colwidth', 100)

---

# Carga de datos

In [3]:
df_genres = pd.read_csv('data/df_genres.csv')
df_item_genre = pd.read_csv('data/df_item_genre.csv')
df_items = pd.read_csv('data/df_items.csv')
df_reviews = pd.read_csv('data/df_reviews.csv')
df_users_items = pd.read_csv('data/df_users_items.csv')
df_users = pd.read_csv('data/df_users.csv')

----

Funciones auxiliares

In [4]:
def items_faltantes(columna_principal,columna_relacionada):
    list_elementos_unicos_de_columna_principal = list(columna_principal.unique())
    list_elementos_unicos_de_columna_relacionada = list(columna_relacionada.unique())
    print(len(list_elementos_unicos_de_columna_principal))
    print(len(list_elementos_unicos_de_columna_relacionada))

    # Convertir las listas a conjuntos
    list_elementos_unicos_de_columna_principal = set(list_elementos_unicos_de_columna_principal)
    list_elementos_unicos_de_columna_relacionada = set(list_elementos_unicos_de_columna_relacionada)

    # Encontrar los elementos que están en set_items_en_df_item_genre pero no en set_items_en_df_items
    elementos_no_en_df_items =   list_elementos_unicos_de_columna_relacionada - list_elementos_unicos_de_columna_principal
    # Obtener la cantidad y los elementos que no están en df_items
    cantidad_elementos_no_en_df_items = len(elementos_no_en_df_items)
    lista_elementos_no_en_df_items = list(elementos_no_en_df_items)

    print("Cantidad de items de la columna relacionada que no se encuentran en la columna principal ", (cantidad_elementos_no_en_df_items))
    print("Elementos que faltan en la columna principal:", lista_elementos_no_en_df_items)
    return lista_elementos_no_en_df_items

----

Las tablas:
- df_genres
- df_item_genre
- df_items
- df_reviews 
- df_users_items
- df_users 

estan relacionadas por lo que no deberíamos tener:
- df_items
    - items en df_item_genre que no esten en df_items
    - items en df_users_items que no esten en df_items
    - items en df_reviews que no esten en  df_items
- df_users
    - users en reviews que no esten en users
    - users en users_items que no esten en users

    - items en df_item_genre que no esten en df_items

In [5]:
items_de_df_item_genre_que_no_estan_en_df_items = items_faltantes(df_items.item_id,df_item_genre.item_id)

30754
28851
Cantidad de items de la columna relacionada que no se encuentran en la columna principal  1230
Elementos que faltan en la columna principal: [696350, 204840, 393270, 344140, 573520, 344150, 630870, 401500, 598110, 335970, 450660, 721000, 598120, 335981, 360560, 98421, 426110, 319620, 688274, 303250, 303251, 712870, 295100, 377020, 327870, 262341, 418000, 237780, 704740, 336100, 737510, 622820, 368870, 491760, 401650, 737530, 762120, 516360, 393500, 295210, 254260, 418110, 205120, 340, 319830, 434520, 426340, 754020, 369010, 311670, 328060, 737660, 278910, 598410, 672140, 467340, 344470, 459160, 393630, 410030, 901553, 328120, 344510, 696770, 770510, 352720, 377300, 369130, 369131, 672240, 737780, 737790, 393730, 713220, 98821, 303630, 606740, 320030, 729640, 508460, 664120, 426560, 246340, 295500, 688730, 303710, 754270, 295530, 688750, 361070, 598640, 443000, 746110, 402050, 574090, 680590, 311950, 426650, 459460, 377540, 525010, 525019, 508650, 353020, 271110, 385820, 328480, 320290, 754470, 680750, 582460, 549700, 328530, 344920, 328560, 246640, 303990, 99200, 476041, 476050, 426900, 345000, 377770, 394190, 590810, 345050, 738270, 590820, 402410, 517100, 705530, 771070, 664580, 500740, 418840, 353320, 369710, 410680, 369720, 386110, 427090, 599140, 615530, 394350, 459890, 328821, 459900, 574590, 337050, 681120, 214190, 410800, 42180, 402630, 443590, 320710, 640200, 566490, 640230, 419060, 34050, 312590, 386320, 58643, 255252, 738580, 58645, 58646, 730390, 58648, 468250, 492820, 492821, 492822, 714020, 533800, 410920, 492840, 353590, 410940, 329020, 689470, 247120, 320860, 320880, 755070, 755071, 755072, 755073, 386430, 34180, 304520, 419210, 411020, 738710, 738711, 337310, 386470, 304570, 468410, 394710, 91609, 419290, 394720, 91616, 550370, 304610, 337380, 386530, 321010, 394740, 509430, 321020, 730630, 730631, 730632, 378380, 697870, 337430, 394790, 329260, 304690, 329270, 362040, 362050, 730700, 362070, 329310, 312930, 706150, 427630, 50820, 329350, 714380, 632470, 329370, 689820, 526000, 526001, 526002, 378550, 378551, 657080, 378552, 272060, 698050, 313030, 427720, 747220, 386780, 771810, 337640, 337660, 337661, 403210, 485130, 681740, 411410, 329500, 321310, 296750, 337710, 1840, 444210, 362300, 730940, 395070, 378690, 304970, 370520, 591710, 386910, 386911, 386913, 370530, 386920, 575340, 542612, 51100, 337830, 501680, 387000, 411580, 313290, 313320, 501740, 428030, 321540, 387080, 706580, 690200, 313372, 616490, 444460, 632880, 428090, 387140, 215120, 567380, 772180, 297050, 772190, 34910, 321630, 329823, 346220, 673910, 755830, 288900, 362630, 673930, 379030, 321690, 379040, 772260, 346290, 747700, 436410, 723130, 362710, 313560, 633060, 690410, 35050, 510190, 395510, 731390, 346370, 502020, 10520, 256280, 452890, 305440, 305450, 608580, 420170, 338250, 772430, 354650, 305510, 379250, 231801, 371070, 379270, 321930, 698770, 264610, 510370, 371140, 321990, 436680, 281050, 231910, 502250, 518660, 2570, 494090, 322060, 346640, 666140, 666150, 420390, 731690, 420410, 338490, 526910, 313920, 346690, 248410, 445020, 764510, 346720, 338540, 264841, 494240, 371370, 682670, 420540, 395970, 420560, 756450, 379620, 412390, 273130, 379630, 674550, 355070, 740100, 11020, 330511, 437010, 723750, 207660, 527150, 404280, 363320, 387910, 543560, 658270, 658271, 494430, 658280, 658304, 658305, 658306, 347010, 617350, 445320, 445321, 445330, 715670, 338840, 396190, 756640, 658340, 297896, 297897, 297898, 314280, 396240, 363480, 355290, 642010, 355300, 551913, 551914, 551915, 732140, 347120, 297970, 355320, 445440, 773120, 396290, 445450, 314390, 298010, 650270, 642080, 379970, 650310, 715850, 470090, 625740, 371800, 715870, 404580, 584820, 257140, 715900, 224380, 724100, 265350, 380050, 617620, 396440, 527520, 396450, 339120, 60600, 298180, 396490, 363740, 355550, 306401, 380130, 617720, 363770, 396540, 388350, 568580, 363780, 363781, 216330, 617740, 404760, 363810, 601380, 298300, 535880, 413000, 413001, 437580, 355660, 675170, 372070, 707950, 454000, 322940, 716170, 339360, 404910, 413110, 413120, 576960, 740800, 650690, 372180, 314850, 708070, 413170, 388600, 306690, 331270, 593431, 339480, 355870, 347680, 265770, 544300, 323120, 708150, 323130, 339520, 323140, 224840, 339530, 323150, 224850, 339540, 323160, 339550, 323170, 323180, 331380, 298620, 347780, 364170, 675480, 667290, 667291, 429730, 306850, 356010, 364210, 372410, 503490, 503500, 659150, 397010, 274130, 372440, 241373, 757480, 274160, 274161, 306930, 478960, 397050, 282370, 347910, 421640, 708360, 347920, 298770, 298771, 372500, 339750, 487210, 380720, 315190, 298810, 675650, 388950, 380760, 323420, 372580, 405350, 438120, 348010, 454510, 397170, 659330, 12170, 12180, 298920, 323500, 733100, 733110, 348090, 634810, 372670, 421830, 503750, 405450, 348110, 364500, 372700, 716780, 503800, 372730, 716800, 380930, 593931, 544790, 348190, 692260, 765990, 667690, 380970, 446510, 618550, 438330, 618560, 585800, 487500, 561240, 585820, 626780, 94304, 430182, 528490, 651370, 503920, 282740, 315510, 299130, 331900, 372860, 315520, 307330, 757900, 200860, 348320, 381090, 569510, 200870, 348330, 372910, 323760, 200880, 708790, 200890, 200891, 438460, 602300, 422080, 602310, 659720, 422160, 422170, 454940, 495900, 602420, 323900, 659780, 758090, 545100, 282960, 430430, 307550, 414050, 741730, 528740, 430440, 725353, 381290, 455020, 364920, 709010, 20902, 405930, 332210, 324030, 348610, 356810, 258512, 29140, 397790, 29150, 602600, 520680, 340460, 356860, 422400, 373250, 348683, 348690, 414240, 324130, 438830, 463410, 340530, 692790, 340540, 250440, 397910, 397920, 373350, 397930, 504430, 316040, 619150, 692880, 316050, 684700, 529060, 365220, 381620, 332470, 316090, 316100, 471750, 373450, 45773, 45774, 45775, 45776, 250600, 381680, 348920, 381716, 684830, 430890, 111403, 365382, 381770, 406350, 324460, 504690, 267130, 390020, 381830, 324490, 340890, 242590, 644000, 635810, 365490, 496570, 308160, 308161, 308162, 308163, 308164, 398280, 308170, 349130, 553940, 717780, 701410, 406500, 488430, 340980, 693280, 521250, 341050, 455740, 365630, 463951, 324690, 398430, 439390, 21600, 300130, 398440, 382060, 267380, 267381, 267382, 463990, 341110, 406660, 275590, 218290, 603320, 701630, 373960, 431320, 423130, 341210, 718050, 644330, 439541, 431360, 398600, 210190, 619790, 570660, 259380, 259381, 677180, 431420, 759100, 759101, 759102, 759110, 546120, 333140, 382310, 226671, 210290, 374130, 349560, 660860, 611710, 267660, 349580, 333200, 439700, 587160, 357790, 423330, 374180, 284070, 718250, 284080, 316850, 349620, 374210, 316869, 316870, 202181, 636360, 423370, 316900, 341480, 390640, 505330, 374260, 333310, 251390, 407040, 349700, 349710, 456210, 423450, 374300, 374301, 595500, 710190, 267830, 390710, 210490, 603720, 439890, 464470, 628310, 374360, 382560, 570980, 398950, 349800, 513640, 300650, 767600, 472690, 382580, 497270, 358010, 349830, 317070, 390800, 333460, 661141, 661142, 612000, 652960, 259760, 620210, 628410, 644800, 423620, 341720, 358110, 554720, 317160, 423670, 300790, 718590, 358150, 374540, 284430, 317210, 603930, 358170, 358180, 677690, 677691, 677692, 300860, 268100, 292690, 366430, 358240, 407400, 604030, 415620, 358280, 317330, 530340, 358330, 628680, 661450, 391130, 333790, 341990, 579560, 366580, 317430, 342010, 301060, 366600, 374800, 358420, 350230, 489500, 366630, 358440, 333890, 333891, 333892, 366660, 432200, 227400, 55370, 366680, 432220, 522333, 424030, 522334, 759900, 374890, 317560, 415870, 325760, 424070, 628870, 628890, 702620, 530595, 530596, 530597, 530598, 530599, 604330, 432310, 350400, 465090, 612570, 268560, 391450, 424220, 334110, 334111, 530720, 334112, 334113, 596260, 366900, 317750, 719160, 260410, 63803, 563530, 383320, 416100, 375140, 678250, 539001, 465290, 383370, 399760, 235920, 432530, 383380, 407960, 645530, 604580, 235940, 268710, 301500, 383430, 621000, 408010, 63950, 317910, 350700, 555510, 334330, 350720, 72200, 334350, 653840, 563730, 432660, 203290, 563740, 432670, 350750, 612900, 358950, 547370, 375340, 768570, 326220, 367180, 440912, 440914, 440915, 383570, 367190, 440920, 440921, 375390, 440930, 596580, 539250, 408180, 326260, 760440, 440960, 440961, 309890, 440962, 318080, 760450, 318090, 416400, 350870, 432810, 375470, 416440, 613050, 522940, 588480, 457410, 359120, 367320, 318170, 260850, 334580, 596730, 375560, 334600, 31500, 768800, 326440, 351020, 318290, 670550, 351070, 285540, 449380, 629610, 318320, 760700, 318340, 416650, 408470, 433050, 293800, 424880, 383920, 752570, 400320, 400330, 555980, 31700, 334810, 318450, 383990, 629751, 285690, 588800, 334860, 547860, 711700, 384020, 384021, 408600, 318490, 351270, 662570, 629820, 506940, 646210, 711760, 375890, 588890, 728170, 457841, 457842, 359540, 253050, 392320, 310410, 334990, 326800, 310420, 736410, 310430, 310440, 375980, 318640, 310450, 367810, 670930, 441560, 433370, 744680, 204010, 449780, 31990, 417020, 441600, 302380, 662830, 769330, 318780, 662850, 679240, 335180, 343380, 384340, 384350, 580960, 531810, 408940, 294260, 359800, 720250, 294270, 376190, 712080, 384410, 73118, 540070, 277930, 359860, 548280, 712120, 261570, 294350, 630230, 261600, 523750, 491010, 24067, 327174, 638470, 384520, 24077, 466450, 409110, 409111, 319000, 319010, 319013, 359980, 335410, 409150, 433730, 548420, 548421, 548422, 253530, 278120, 466541, 376440, 392830, 417420, 409230, 319120, 351890, 384670, 294560, 695970, 491180, 573110, 450240, 368320, 556740, 458440, 458443, 65230, 311000, 384730, 737000, 737001, 737002, 204522, 204523, 311020, 204524, 753390, 417520, 458490, 392960, 409350, 335640, 606000, 368440, 360250, 335680, 401220, 614230, 270170, 720730, 671580, 622440, 491370, 319340, 491380, 761720, 311161, 311162, 311163, 311164, 630650, 573320, 401300, 90007, 245660, 688030, 384930, 335800, 90044, 516030, 90047, 344000, 630720, 704450, 401350, 696280, 221169, 401400, 475130, 475131, 475132]

    - items en df_users_items que no esten en df_items

In [6]:
items_de_df_users_items_que_no_estan_en_df_items = items_faltantes(df_items.item_id,df_users_items.item_id)

30754
10050
Cantidad de items de la columna relacionada que no se encuentran en la columna principal  1677
Elementos que faltan en la columna principal: [40960, 245760, 262150, 475150, 221200, 352280, 24600, 360480, 352290, 221220, 204840, 24620, 254000, 24630, 57400, 335930, 344130, 254020, 335950, 24660, 254040, 100, 41070, 368750, 344180, 221300, 417910, 213120, 516230, 393360, 458900, 368790, 221340, 8350, 360610, 8360, 385200, 221360, 8370, 254130, 24760, 8380, 352450, 295110, 98510, 418000, 286930, 336100, 24820, 221430, 49400, 41210, 524540, 24830, 368900, 319750, 24850, 24860, 377120, 360760, 16700, 418110, 442700, 57680, 340, 319830, 434520, 16730, 385370, 352610, 295270, 418150, 409960, 409970, 221560, 459130, 409980, 328060, 205180, 278910, 49540, 409990, 311700, 459160, 65950, 90530, 434600, 360880, 467380, 8640, 205250, 33220, 328140, 352720, 508380, 33250, 33260, 319980, 270830, 377330, 246260, 360950, 33270, 238070, 107000, 319990, 33280, 320000, 270850, 467460, 246280, 393740, 205330, 238110, 49700, 205350, 311850, 369200, 238130, 426560, 213570, 33350, 467530, 508490, 328270, 98900, 238170, 516700, 303710, 221790, 358330, 303720, 467560, 57970, 483960, 17020, 246400, 508550, 500360, 303760, 33440, 344750, 508590, 90800, 254650, 492220, 443080, 303820, 492240, 33500, 33510, 303850, 320240, 459510, 336630, 33530, 426750, 41730, 33540, 402180, 385800, 205590, 230170, 33580, 320300, 320310, 344900, 377670, 246600, 377680, 475990, 385880, 377690, 361320, 435060, 99200, 295810, 107400, 312200, 517000, 336790, 107430, 361400, 271290, 17340, 58300, 410560, 287680, 50120, 492490, 33740, 230350, 369620, 33750, 426970, 205790, 410590, 33780, 17400, 295930, 238590, 484350, 254980, 492560, 508950, 377880, 58400, 255010, 402470, 402471, 402472, 402473, 402474, 402475, 402476, 402477, 402478, 402479, 402480, 402481, 402482, 402483, 402484, 402485, 402486, 402487, 402488, 402489, 402490, 402491, 402492, 402493, 402494, 402495, 386110, 312390, 500810, 410700, 320590, 107600, 312410, 263260, 468060, 205930, 492660, 246900, 33910, 238710, 9340, 50310, 418950, 304270, 58510, 402591, 402592, 402593, 402594, 402595, 402596, 402597, 402598, 402599, 361640, 402600, 402601, 402602, 402603, 402604, 214190, 402605, 42160, 402606, 402607, 402608, 58540, 91310, 451760, 9400, 17600, 214210, 402630, 34000, 214230, 50400, 361710, 25840, 361720, 214270, 361730, 25860, 378120, 361740, 25870, 263440, 386320, 361750, 1309, 361760, 1313, 279840, 222500, 214310, 361770, 304430, 214320, 361780, 329020, 378180, 525640, 247120, 378020, 238960, 411000, 320890, 230780, 107900, 460160, 34180, 17800, 17810, 353690, 34220, 345520, 370100, 50640, 50650, 370140, 99810, 394740, 99830, 222710, 255480, 9740, 255500, 288270, 321040, 345620, 321070, 34330, 312860, 255520, 411181, 411182, 411183, 411184, 411185, 99890, 468530, 411186, 411187, 411190, 411188, 411191, 411192, 411189, 411194, 411193, 108100, 99920, 362070, 321110, 394840, 271970, 222820, 214640, 50800, 239220, 394870, 312960, 9860, 501380, 50820, 34440, 9870, 42640, 34450, 42650, 34460, 263840, 296610, 42660, 485040, 18100, 222900, 42680, 403130, 272060, 18110, 419520, 42690, 362180, 362190, 50900, 42710, 370390, 362200, 394970, 362210, 403170, 42730, 362220, 386800, 50930, 362230, 321270, 304890, 362240, 9990, 50950, 362250, 231180, 10000, 362260, 444180, 362270, 321310, 345890, 50980, 50990, 239410, 321330, 51000, 288570, 362300, 214850, 42830, 34650, 239450, 460640, 10080, 51040, 272230, 34670, 460660, 42870, 280440, 296830, 493440, 1920, 427920, 509840, 206740, 51100, 10170, 501690, 468930, 10190, 501720, 255960, 247770, 272350, 501740, 296950, 321540, 428040, 403470, 18450, 215060, 247830, 18460, 501800, 452650, 34860, 444460, 280620, 100410, 18490, 297020, 264260, 460870, 419910, 436300, 215120, 2130, 297060, 43110, 272490, 264300, 346220, 247930, 436350, 305280, 297090, 206980, 313480, 444560, 43160, 313500, 346270, 223390, 10400, 264360, 452780, 346290, 10430, 35010, 354510, 207060, 35030, 280790, 485590, 354520, 329950, 354530, 354540, 10480, 231670, 354550, 420090, 362750, 346370, 223490, 420110, 272670, 346400, 10530, 223530, 10540, 395570, 321860, 485700, 354650, 297310, 10590, 256350, 305510, 207210, 2430, 330110, 403840, 313730, 264580, 313740, 223630, 330130, 412050, 10650, 256410, 223650, 10660, 338340, 428460, 387500, 297390, 330160, 223670, 256440, 444860, 10690, 10700, 338390, 281050, 272860, 2525, 338400, 502240, 330210, 231910, 297450, 2545, 2550, 215550, 2570, 518670, 354830, 264730, 240160, 354850, 281130, 453170, 240180, 231990, 354870, 346680, 371260, 453190, 240200, 19020, 27220, 428630, 371290, 248410, 354910, 461410, 100970, 338540, 223870, 2690, 363150, 35470, 469650, 19090, 27300, 338600, 35500, 314030, 35510, 240320, 510660, 2760, 395980, 379600, 445140, 232150, 355030, 2790, 387820, 371440, 240380, 355070, 461570, 404230, 264970, 11020, 289550, 232210, 379670, 420630, 11060, 265020, 224060, 404290, 428870, 240460, 297810, 109400, 109410, 11120, 2930, 404370, 11170, 314280, 11180, 3000, 486340, 363480, 224220, 44000, 437220, 519140, 469990, 273390, 338930, 289780, 265210, 330760, 207890, 347160, 453670, 322600, 257080, 224320, 339010, 3150, 347220, 224340, 3160, 281690, 371810, 404580, 396390, 224360, 494710, 289910, 224380, 3200, 273550, 3220, 11420, 208030, 289950, 224420, 339120, 11440, 380080, 404660, 265400, 224440, 216250, 60600, 298180, 265420, 527570, 19680, 347360, 347370, 462060, 11500, 486640, 404730, 11520, 437510, 36110, 265490, 347410, 44310, 36120, 11550, 44320, 445730, 3370, 216370, 298300, 36160, 273730, 216390, 36170, 314700, 413010, 36190, 36200, 232810, 200060, 273790, 19840, 511360, 519560, 519561, 519562, 519563, 519564, 519565, 3470, 494990, 519566, 519567, 28050, 519568, 519569, 519570, 519571, 519572, 519573, 519574, 519575, 519576, 519577, 519578, 241070, 404910, 265650, 298420, 404920, 445880, 486840, 445900, 495060, 314850, 224740, 347630, 413170, 503300, 19990, 462370, 249380, 265770, 3630, 405040, 3650, 355910, 61000, 339530, 364110, 61010, 339540, 44630, 454230, 331360, 396900, 290410, 44680, 200330, 306830, 388750, 200350, 347820, 323250, 405180, 462530, 323270, 274130, 208610, 315110, 503530, 282350, 478960, 306930, 405240, 323320, 282370, 388870, 503560, 36620, 36630, 397080, 347930, 233250, 61220, 495400, 61230, 421700, 405320, 200530, 397140, 36700, 380770, 257890, 495460, 421730, 307050, 495470, 454510, 225140, 3970, 12170, 331660, 12180, 290710, 225180, 372650, 233390, 12210, 200630, 339900, 331710, 372670, 290750, 225220, 12230, 12240, 274390, 12250, 503770, 208860, 12260, 217060, 241640, 356330, 520180, 217080, 413690, 299010, 487430, 290830, 274450, 421910, 307230, 364590, 266290, 233530, 438330, 315450, 462910, 315460, 421960, 454730, 389200, 12370, 274520, 61530, 12380, 331880, 258160, 282740, 340090, 241790, 446590, 37000, 233610, 340110, 413851, 413852, 413853, 233630, 413855, 413854, 413856, 413858, 413859, 381090, 413857, 266410, 389300, 200900, 266450, 381140, 422100, 438490, 381150, 4320, 315640, 12550, 209170, 381210, 373021, 373022, 373023, 446750, 356640, 94500, 94510, 397620, 266550, 94520, 201020, 323900, 94530, 241990, 37200, 282960, 373080, 250200, 291170, 430440, 20840, 373100, 274800, 373110, 266620, 250240, 37250, 233860, 94600, 291210, 217490, 94610, 102820, 250280, 299440, 414130, 29110, 4540, 209340, 4550, 12750, 29140, 29150, 225760, 340450, 201190, 37350, 315880, 340460, 4600, 12800, 406020, 234000, 373280, 12840, 37420, 496180, 12860, 340540, 201280, 389700, 340550, 201290, 324170, 234060, 266840, 21080, 496240, 201330, 21110, 299640, 4730, 21120, 496260, 258700, 381590, 438940, 21170, 299700, 512710, 316110, 471770, 4830, 250600, 406261, 406263, 340730, 209660, 217860, 488200, 242460, 209710, 242480, 29500, 234310, 45900, 406350, 29520, 299860, 13140, 340820, 29530, 447330, 299890, 381810, 250740, 217980, 431000, 242590, 406440, 373680, 349110, 390070, 259000, 504770, 373700, 29640, 29650, 496600, 201700, 29680, 463860, 332790, 250870, 414730, 37900, 447500, 226320, 390160, 37910, 29720, 357400, 201760, 37920, 234530, 37930, 316460, 255030, 37940, 218170, 37950, 37970, 447570, 37980, 21600, 218210, 201830, 37990, 21610, 38010, 46210, 38020, 46220, 201870, 38030, 46230, 373920, 38050, 431270, 300200, 332970, 38060, 267440, 324790, 292030, 341190, 13510, 218310, 259280, 218330, 21730, 259300, 210150, 488680, 46320, 234740, 21750, 46330, 431360, 21760, 95500, 488720, 496920, 267550, 382240, 259360, 382260, 38200, 456000, 365890, 13640, 38220, 447820, 218450, 46420, 382300, 46430, 38240, 357730, 218470, 202090, 46460, 374140, 13700, 447880, 349580, 21900, 226700, 439700, 21910, 316830, 21920, 316840, 210350, 21950, 243140, 447940, 226760, 357840, 21970, 210390, 447960, 234980, 21990, 46570, 210410, 243180, 325100, 251390, 349700, 407060, 226840, 423460, 407090, 349750, 210490, 448060, 489020, 38480, 464470, 505440, 243300, 71270, 464490, 374380, 497270, 243320, 22140, 284290, 38530, 448130, 464540, 104100, 226980, 202410, 259760, 251570, 243380, 317110, 423620, 407250, 399060, 341720, 333530, 251610, 71390, 423650, 497380, 218860, 374510, 71420, 415490, 456450, 251670, 399130, 358170, 423710, 333600, 407330, 358180, 366400, 317250, 292680, 235340, 505680, 55130, 358240, 218980, 243560, 317300, 431990, 243580, 358280, 251790, 489360, 317330, 55190, 399260, 423840, 456610, 333740, 374700, 38830, 374701, 374702, 374703, 374704, 374705, 464820, 374709, 374710, 374711, 374712, 374706, 374714, 374707, 374708, 374717, 374713, 374719, 374715, 374716, 374718, 374720, 374721, 440260, 374722, 448460, 268240, 432080, 227280, 6100, 202710, 374743, 374742, 374744, 22490, 374745, 382940, 374746, 391130, 325600, 423920, 38900, 489460, 227320, 382970, 333820, 333830, 366600, 284680, 440330, 456720, 358420, 432150, 358430, 333860, 497700, 358440, 464940, 96300, 210990, 383030, 399420, 251970, 55370, 358480, 39000, 424030, 383080, 211050, 202860, 440430, 440431, 440432, 440433, 440434, 440435, 440436, 440437, 440438, 6270, 63620, 383110, 481420, 63630, 96400, 497810, 497811, 497812, 6290, 497813, 252050, 293010, 63640, 465050, 243870, 211120, 407730, 235700, 432310, 6330, 407740, 514240, 6340, 211140, 407750, 6350, 334040, 497880, 243930, 399580, 350430, 391390, 407780, 202990, 235760, 358640, 350450, 399610, 366844, 293140, 276770, 465190, 252210, 440630, 260410, 39250, 407890, 399700, 407891, 285010, 317780, 39260, 358750, 227680, 448870, 285030, 432490, 342380, 448880, 227700, 31100, 268670, 473470, 399750, 31110, 227720, 39310, 31120, 473490, 219540, 39320, 31130, 375200, 293280, 268710, 301480, 6570, 367020, 407980, 326060, 211380, 293300, 301500, 375230, 473540, 350660, 39370, 63950, 342480, 219600, 448980, 383460, 473580, 350700, 293360, 203250, 31220, 457210, 31230, 72200, 31240, 416270, 31250, 473620, 293400, 203290, 31260, 268830, 473630, 31270, 473640, 473650, 23100, 244290, 23120, 39510, 23130, 219740, 481890, 23140, 375400, 39530, 72300, 465540, 383620, 318090, 227980, 424590, 219800, 481950, 23200, 260770, 6820, 359080, 39600, 490160, 277170, 31410, 293560, 39610, 441020, 39620, 432850, 15060, 47830, 211670, 285400, 219870, 457440, 359140, 47850, 277230, 391920, 408330, 31500, 326420, 47900, 39710, 506660, 15140, 473900, 15150, 432950, 351040, 23360, 334670, 23390, 342880, 228200, 392050, 15220, 359290, 392060, 15230, 23440, 220050, 7060, 211880, 416680, 15280, 416690, 367540, 105400, 15290, 375740, 293820, 433100, 203730, 31700, 105430, 23510, 506840, 236510, 236530, 48120, 48160, 203810, 252970, 400430, 48180, 523320, 523321, 269370, 523322, 523323, 523324, 523325, 523326, 40000, 523327, 523328, 523329, 203850, 367690, 269390, 56400, 334930, 7250, 48210, 326740, 449630, 441451, 441452, 441453, 48240, 441457, 244850, 416880, 400510, 294020, 269450, 72850, 375960, 449690, 310450, 15540, 15560, 253130, 457930, 228560, 212180, 457940, 523481, 523482, 523483, 523485, 523486, 523487, 523490, 335080, 7400, 113900, 449780, 212220, 449800, 7440, 212240, 7450, 236830, 343330, 367910, 326950, 302380, 7470, 261430, 269630, 7500, 269650, 400740, 204140, 408940, 400760, 359800, 32130, 245130, 384400, 212370, 343450, 269730, 384421, 384422, 277930, 359850, 40370, 327100, 277950, 261570, 261600, 310760, 253430, 507390, 359940, 458250, 73230, 106000, 228880, 458260, 106010, 384540, 253470, 458270, 458280, 327210, 400940, 24120, 7740, 458300, 441920, 24130, 15940, 458310, 24140, 65100, 228940, 458320, 319060, 269910, 24150, 392790, 253530, 351840, 7780, 212580, 24170, 15980, 15990, 7800, 7810, 278150, 24210, 24220, 466590, 392870, 7850, 458410, 319150, 7870, 278210, 360130, 7880, 32460, 425680, 425681, 425682, 425683, 425684, 425685, 360150, 425686, 425687, 425689, 16090, 425688, 7900, 204510, 409310, 311010, 7910, 409320, 351980, 229100, 65260, 491250, 474870, 442110, 302850, 48900, 294660, 7970, 7980, 220980, 7990, 442180, 270170, 434010, 458590, 8040, 466800, 8060, 24470, 221080, 384930, 212910, 32690, 475060, 24500, 483260, 32700, 434110, 417730, 311240, 466890, 40920, 237530, 475100, 8160, 466920, 458730, 393200, 90100, 319480]

    - items en df_reviews que no esten en  df_items

In [7]:
items_de_df_reviews_que_no_estan_en_df_items = items_faltantes(df_items.item_id,df_reviews.item_id)

30754
3488
Cantidad de items de la columna relacionada que no se encuentran en la columna principal  551
Elementos que faltan en la columna principal: [245760, 315392, 262150, 475150, 290830, 274450, 247830, 313372, 307230, 360480, 221220, 241700, 333860, 501800, 452650, 96300, 210990, 41010, 266290, 57400, 297020, 34880, 403520, 251970, 315460, 366660, 55370, 344140, 24660, 274520, 39000, 34910, 450660, 43110, 383080, 211050, 41070, 258160, 221300, 282740, 417910, 331900, 213120, 233610, 444560, 96400, 293010, 43160, 313500, 223390, 233630, 243870, 264360, 266410, 452780, 221360, 385200, 254130, 200900, 295110, 422100, 280790, 334040, 418010, 438490, 243930, 399580, 329950, 336100, 368870, 235760, 401650, 221430, 231670, 49400, 315640, 366844, 366845, 223490, 346370, 368900, 420110, 381210, 24860, 446750, 356640, 276770, 35110, 397610, 254260, 397620, 360760, 260410, 321860, 57680, 340, 92500, 317780, 270680, 373080, 16730, 385370, 323930, 256350, 358750, 227680, 295270, 430440, 20840, 207210, 342380, 227700, 373110, 328060, 278910, 268670, 313730, 49540, 233860, 291210, 344460, 313740, 223630, 354702, 410, 256410, 375200, 264610, 338340, 102820, 301480, 414130, 336310, 223670, 444860, 209340, 4540, 375230, 33220, 4550, 213450, 12750, 342480, 219600, 281050, 322010, 338400, 330210, 383460, 231910, 315880, 340460, 473580, 377330, 256500, 31220, 360950, 238070, 33280, 422400, 270850, 12800, 246280, 72200, 2570, 317960, 322060, 234000, 322070, 264730, 203290, 33310, 268830, 354850, 205350, 338470, 31270, 281130, 404011, 404012, 404013, 369200, 401980, 340540, 229950, 334400, 324170, 201290, 326220, 23120, 39510, 266840, 238170, 248410, 219740, 221790, 338540, 496240, 299640, 17020, 463490, 309890, 258700, 363150, 424590, 338580, 219800, 33440, 70310, 246440, 412332, 344750, 508590, 314030, 21170, 31410, 299700, 293560, 254650, 240320, 2760, 322250, 303820, 395980, 4830, 219870, 264930, 250600, 371440, 340730, 240380, 402180, 340740, 385800, 211720, 408330, 11020, 314130, 379670, 320300, 15150, 224060, 351040, 334660, 234310, 240460, 377680, 297810, 13140, 299860, 475990, 109400, 109410, 265061, 246640, 299890, 435060, 250740, 267130, 359290, 15230, 295810, 220050, 242590, 11170, 373680, 416690, 203701, 105400, 271290, 240570, 322490, 209873, 203730, 330710, 105430, 363480, 410590, 236510, 437220, 201700, 469990, 273390, 332790, 250870, 265210, 316410, 328700, 238590, 445440, 414730, 447500, 226320, 207890, 384020, 384021, 347160, 224280, 357400, 234530, 203810, 48180, 410680, 257080, 269370, 224320, 203850, 320590, 269390, 107600, 56400, 334930, 281690, 201830, 205930, 48240, 244850, 246900, 267380, 267381, 9340, 509060, 294020, 275590, 269450, 304270, 201870, 72850, 375960, 490650, 11420, 289950, 208030, 224420, 361640, 332970, 58540, 91310, 214190, 42160, 339120, 289970, 224440, 216250, 292030, 298180, 91333, 402630, 218310, 13510, 15560, 228560, 212180, 214230, 218330, 19680, 212220, 431360, 441600, 378120, 449800, 263440, 44310, 496920, 267550, 44320, 343330, 3370, 302380, 304430, 214320, 259380, 259381, 13640, 314700, 447820, 247120, 370002, 218450, 269650, 38240, 218470, 232810, 202090, 238960, 359800, 107900, 228740, 447880, 245130, 226700, 349580, 3470, 28050, 212370, 353690, 269730, 388520, 277930, 345520, 265650, 370100, 468410, 277950, 261570, 245190, 21970, 50650, 357850, 99810, 21995, 243180, 325100, 347630, 413170, 222710, 253430, 255480, 349700, 359940, 255500, 321040, 228880, 407060, 34330, 230940, 374300, 374301, 255520, 249380, 355880, 265770, 34350, 226880, 441920, 331330, 433730, 323140, 228940, 364110, 38480, 220760, 282201, 253530, 22110, 396900, 212580, 71270, 323180, 319090, 239220, 394870, 243320, 349830, 323210, 9870, 306830, 351890, 42650, 319130, 200350, 226980, 319150, 251570, 222900, 417460, 317110, 42680, 439995, 272060, 18110, 403150, 407250, 341720, 394970, 251610, 71390, 282350, 202485, 323320, 337660, 337661, 388870, 358150, 231180, 36620, 378641, 378642, 378645, 36630, 251670, 378648, 378649, 333600, 210720, 233250, 407330, 61220, 1840, 239410, 214850, 317250, 421700, 235340, 231250, 239450, 270170, 458590, 380770, 257890, 218980, 243560, 307050, 34670, 487280, 225140, 509840, 427920, 24470, 221080, 51100, 423840, 456610, 323500, 38830, 12210, 24500, 200630, 335800, 348090, 348091, 290750, 331710, 300991, 434110, 311240, 227280, 268240, 6100, 202710, 503770, 272350, 333790, 325600, 217060, 241640, 458730, 393200, 231410, 38900, 227320]

crearemos una lista de estos items

In [8]:
items_sobrantes = set(items_de_df_item_genre_que_no_estan_en_df_items + items_de_df_users_items_que_no_estan_en_df_items +items_de_df_reviews_que_no_estan_en_df_items)

In [9]:
len(items_sobrantes)

2867

In [10]:
df_items[df_items.item_id==245760]

Empty DataFrame
Columns: [item_id, title, url, release_date, developer, price]
Index: []

Existen 2867 items que se encuentran en las tablas relacionadas pero no en la tabla donde se almacena la info de items.
Para que la información sea consistente eliminaremos estos items de los df.

Eliminamos items de df_item_genre

In [11]:
df_item_genre[df_item_genre.item_id.isin(items_sobrantes)]

       item_id      genres
32      768800      Casual
33      768800       Indie
34      768800      Racing
35      768800  Simulation
36      768570      Action
...        ...         ...
71528   771810      Action
71529   771810   Adventure
71530   771810       Indie
71535   769330      Casual
71536   769330       Indie

[3199 rows x 2 columns]

In [12]:
df_item_genre = df_item_genre[~(df_item_genre.item_id.isin(items_sobrantes))]

Eliminamos items de df_users_item

In [13]:
df_users_items[df_users_items.item_id.isin(items_sobrantes)]

                   user_id  item_id  playtime_forever
12       76561197970982479      340                37
16       76561197970982479     9340               692
31       76561197970982479    23120                53
34       76561197970982479    35010               570
40       76561197970982479    24860               437
...                    ...      ...               ...
3246314  76561198312638244   202990                21
3246315  76561198312638244   212910               490
3246337  76561198320038728    39000                71
3246342  76561198320136420   496920                 2
3246351  76561198329548331   519140                 3

[449797 rows x 3 columns]

In [14]:
df_users_items = df_users_items[~(df_users_items.item_id.isin(items_sobrantes))]

Eliminamos items de df_reviews

In [15]:
df_reviews[df_reviews.item_id.isin(items_sobrantes)]

,user_id,item_id,recommend,posted_date,year,sentiment_analysis
2,76561197970982479,43110,True,2011-04-21,2011,2
3,js41637,251610,True,2014-06-24,2014,2
23,76561198089393905,72850,True,2015-02-01,2015,0
42,76561198043472122,33440,False,2014-12-19,2014,0
67,76561198054540475,12210,True,2015-02-13,2015,2
...,...,...,...,...,...,...
52169,76561198222628548,359800,True,2015-04-10,2015,0
52188,wayfeng,369200,True,NaN,0,2
52209,76561198267374962,369200,True,2015-12-29,2015,2
52210,76561198270958927,381210,True,NaN,0,0
52225,76561198296402247,280790,True,NaN,0,0

In [16]:
df_reviews = df_reviews[~(df_reviews.item_id.isin(items_sobrantes))]

    - users en reviews que no esten en users

In [17]:
items_de_df_reviews_que_no_estan_en_df_users = items_faltantes(df_users.user_id,df_reviews.user_id)

70912
21584
Cantidad de items de la columna relacionada que no se encuentran en la columna principal  0
Elementos que faltan en la columna principal: []

    - users en users_items que no esten en users

In [18]:
items_de_df_users_items_que_no_estan_en_df_users = items_faltantes(df_users.user_id,df_users_items.user_id)

70912
67829
Cantidad de items de la columna relacionada que no se encuentran en la columna principal  0
Elementos que faltan en la columna principal: []

Podemos ver que no existen usuarios en df_reviews y df_users_items que no se encuentren en df_users

Las tablas:
- df_genres
- df_item_genre
- df_items
- df_reviews 
- df_users_items
- df_users

In [19]:
df_genres.to_csv("data/df_genres.csv",index=False)
df_item_genre.to_csv("data/df_item_genre.csv",index=False)
df_users_items.to_csv("data/df_users_items.csv",index=False)
df_reviews.to_csv("data/df_reviews.csv",index=False)
df_users_items.to_csv("data/df_users_items.csv",index=False)